# Taps
tap "minio/stable"
tap "stripe/stripe-cli"
tap "stripe/stripe-mock"

# Binaries (Formulas)
brew "argocd"
brew "autojump"
brew "awscli"
brew "bash"
brew "bat"
brew "coreutils"
brew "ffmpeg"
brew "gh"
brew "git"
brew "go"
brew "grep"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kustomize"
brew "mackup"
brew "mas"
brew "minio/stable/mc"
brew "neovim"
brew "pipx"
brew "pkg-config"
brew "podman"
brew "podman-compose"
brew "pre-commit"
brew "ripgrep"
brew "rust"
brew "stripe/stripe-cli/stripe"
brew "stripe/stripe-mock/stripe-mock"
brew "task"
brew "tree"
brew "yarn"
brew "terraform"

# Spatie Medialibrary
brew "jpegoptim"
brew "optipng"
brew "pngquant"
brew "svgo"
brew "gifsicle"

# Apps (Casks)
cask "caffeine"
cask "figma"
cask "firefox"
cask "github"
cask "google-chrome"
cask "imageoptim"
cask "qlmarkdown"
cask "screen-studio"
cask "slack"
cask "visual-studio-code"
cask "warp"
cask "dbeaver-community"
cask "iterm2"

# Fonts
cask "font-fira-code-nerd-font"
