#!/bin/bash

# tailscale-mutt-setup.sh: Set up a secondary Tailscale instance for work VPN
# Run as admin (with sudo). Idempotent — safe to re-run.
#
# Creates:
#   - systemd service: tailscaled-mutt
#   - wrapper script:  /usr/local/bin/tailscale-mutt
#   - sudoers drop-in: /etc/sudoers.d/tailscale-mutt
#
# The secondary instance uses:
#   - Separate TUN device (ts-mutt), socket, state dir, port
#   - netfilter-mode=off to avoid routing conflicts with primary tailscale
#   - DevicePolicy=closed to avoid TPM contention
#
# Usage:
#   sudo ./tailscale-mutt-setup.sh <user>
#   sudo ./tailscale-mutt-setup.sh mutt
#
# Then as the user:
#   tailscale-mutt up --authkey=tskey-auth-...
#   tailscale-mutt status
#   tailscale-mutt down
#
# See: docs/ecryptfs.md (for encrypted home setup)
#      docs/tailscale-mutt.md (for this setup)

set -e

USER="${1:?Usage: $0 <user>}"

STATE_DIR="/var/lib/tailscale-mutt"
SOCKET="/run/tailscale-mutt.sock"
SERVICE="tailscaled-mutt"
PORT=41642
TUN="ts-mutt"
WRAPPER="/usr/local/bin/tailscale-mutt"
SUDOERS_FILE="/etc/sudoers.d/tailscale-mutt"
TAILSCALE_BIN="$(command -v tailscale)"
SYSTEMCTL_BIN="$(command -v systemctl)"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: run with sudo"
    exit 1
fi

if ! id "$USER" &>/dev/null; then
    echo "Error: user '$USER' does not exist"
    exit 1
fi

if ! command -v tailscaled &>/dev/null; then
    echo "Error: tailscale not installed"
    exit 1
fi

echo "Setting up secondary Tailscale instance"
echo "  user: $USER"
echo "  port: $PORT"
echo "  tun:  $TUN"
echo ""

# --- Clean up old per-env services if they exist ---
for env in dev stage prod; do
    old_svc="tailscaled-mutt-${env}"
    if systemctl is-active --quiet "$old_svc" 2>/dev/null; then
        systemctl stop "$old_svc"
        systemctl disable "$old_svc"
        rm -f "/etc/systemd/system/${old_svc}.service"
        rm -f "/usr/local/bin/tailscale-mutt-${env}"
        rm -rf "/var/lib/tailscale-mutt-${env}"
        echo "  cleanup: removed old $old_svc"
    elif [ -f "/etc/systemd/system/${old_svc}.service" ]; then
        rm -f "/etc/systemd/system/${old_svc}.service"
        rm -f "/usr/local/bin/tailscale-mutt-${env}"
        rm -rf "/var/lib/tailscale-mutt-${env}"
        echo "  cleanup: removed old $old_svc (was inactive)"
    fi
done

# --- State directory ---
mkdir -p "$STATE_DIR"

# --- systemd service ---
cat > /etc/systemd/system/${SERVICE}.service <<EOF
[Unit]
Description=Tailscale (secondary - work VPN)
After=network-pre.target NetworkManager.service systemd-resolved.service tailscaled.service
Wants=network-pre.target
# Start after primary tailscale to avoid conflicts
Requires=tailscaled.service

[Service]
ExecStart=/usr/sbin/tailscaled --state=${STATE_DIR}/tailscaled.state --socket=${SOCKET} --port=${PORT} --tun=${TUN}
Restart=on-failure
RestartSec=5
# TPM errors are handled gracefully by tailscaled internally (no DevicePolicy needed)

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "$SERVICE"
echo "  service: $SERVICE"

# --- wrapper script ---
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Tailscale wrapper: secondary work VPN instance
# See: docs/tailscale-mutt.md
SOCKET="${SOCKET}"
SERVICE="${SERVICE}"

case "\$1" in
    start|stop|restart)
        sudo ${SYSTEMCTL_BIN} "\$1" "\$SERVICE"
        ;;
    "")
        echo "Usage: tailscale-mutt <command>"
        echo ""
        echo "  up [--authkey=...]   Connect to work tailnet"
        echo "  down                 Disconnect"
        echo "  status               Show connection status"
        echo "  ip                   Show Tailscale IP"
        echo "  ping <host>          Ping a tailnet host"
        echo ""
        echo "  start                Start daemon"
        echo "  stop                 Stop daemon"
        echo "  restart              Restart daemon"
        ;;
    *)
        sudo ${TAILSCALE_BIN} --socket="\$SOCKET" "\$@"
        ;;
esac
EOF
chmod +x "$WRAPPER"
echo "  wrapper: $WRAPPER"

# --- sudoers drop-in ---
cat > "$SUDOERS_FILE" <<EOF
# Allow $USER to manage the secondary tailscale instance (no password)
# Auto-generated by tailscale-mutt-setup.sh — do not edit manually
$USER ALL=(ALL) NOPASSWD: ${TAILSCALE_BIN} --socket=${SOCKET} *
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} start ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} stop ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} restart ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} status ${SERVICE}
EOF
chmod 440 "$SUDOERS_FILE"

if ! visudo -cf "$SUDOERS_FILE" &>/dev/null; then
    echo "  ERROR: sudoers syntax invalid, removing"
    rm -f "$SUDOERS_FILE"
    exit 1
fi
echo "  sudoers: $SUDOERS_FILE"

# --- Set operator so $USER can run tailscale up/down/set without sudo ---
tailscale --socket="$SOCKET" set --operator="$USER" 2>/dev/null || true
echo "  operator: $USER"

echo ""
echo "Done. Connect as '$USER':"
echo "  tailscale-mutt up --authkey=tskey-auth-..."
echo ""
echo "Verify personal tailscale is unaffected:"
echo "  tailscale status"
