#!/bin/bash

# tailscale-mutt-setup.sh: Set up Tailscale instances for MuttData environments
# Run as admin (with sudo). Idempotent — safe to re-run.
#
# Creates per-env:
#   - systemd service: tailscaled-mutt-<env>
#   - wrapper script:  /usr/local/bin/tailscale-mutt-<env>
#   - sudoers drop-in: /etc/sudoers.d/tailscale-mutt (covers all envs)
#
# Usage:
#   sudo ./tailscale-mutt-setup.sh <user> <env>
#   sudo ./tailscale-mutt-setup.sh mutt dev
#   sudo ./tailscale-mutt-setup.sh mutt stage
#   sudo ./tailscale-mutt-setup.sh mutt prod
#
# Then as mutt:
#   tailscale-mutt-dev up --authkey=tskey-...
#   tailscale-mutt-stage up --authkey=tskey-...
#   tailscale-mutt-prod up --authkey=tskey-...

set -e

USER="${1:?Usage: $0 <user> <env>}"
ENV="${2:?Usage: $0 <user> <env> (env: dev|stage|prod)}"

# Port assignment per env
case "$ENV" in
    dev)   PORT=41642 ;;
    stage) PORT=41643 ;;
    prod)  PORT=41644 ;;
    *)     echo "Error: env must be dev, stage, or prod"; exit 1 ;;
esac

STATE_DIR="/var/lib/tailscale-mutt-${ENV}"
SOCKET="/run/tailscale-mutt-${ENV}.sock"
SERVICE="tailscaled-mutt-${ENV}"
WRAPPER="/usr/local/bin/tailscale-mutt-${ENV}"
SUDOERS_FILE="/etc/sudoers.d/tailscale-mutt"
TAILSCALE_BIN="$(command -v tailscale)"
SYSTEMCTL_BIN="$(command -v systemctl)"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: run with sudo"
    exit 1
fi

if ! id "$USER" &>/dev/null; then
    echo "Error: user '$USER' does not exist"
    exit 1
fi

if ! command -v tailscaled &>/dev/null; then
    echo "Error: tailscale not installed"
    exit 1
fi

echo "Setting up Tailscale instance: mutt-${ENV} (port ${PORT})"
echo "  user: $USER"
echo ""

# --- State directory ---
mkdir -p "$STATE_DIR"
echo "  state: $STATE_DIR"

# --- systemd service ---
cat > /etc/systemd/system/${SERVICE}.service <<EOF
[Unit]
Description=Tailscale (MuttData ${ENV})
After=network-pre.target NetworkManager.service systemd-resolved.service
Wants=network-pre.target

[Service]
# No ExecStartPre cleanup — causes TPM contention with primary tailscaled
ExecStart=/usr/sbin/tailscaled --state=${STATE_DIR}/tailscaled.state --socket=${SOCKET} --port=${PORT}
Restart=on-failure
# Block TPM access to avoid /dev/tpmrm0 contention (state stored unencrypted)
DevicePolicy=closed
DeviceAllow=/dev/net/tun rw
DeviceAllow=/dev/null rw
DeviceAllow=/dev/urandom r

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "$SERVICE"
echo "  service: $SERVICE (port $PORT)"

# --- wrapper script ---
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Tailscale wrapper: MuttData ${ENV}
SOCKET="${SOCKET}"
SERVICE="${SERVICE}"

case "\$1" in
    start|stop|restart|status-svc)
        cmd="\$1"
        [ "\$cmd" = "status-svc" ] && cmd="status"
        sudo ${SYSTEMCTL_BIN} "\$cmd" "\$SERVICE"
        ;;
    "")
        echo "Usage: tailscale-mutt-${ENV} <command>"
        echo ""
        echo "  up [--authkey=...]   Connect to MuttData ${ENV} tailnet"
        echo "  down                 Disconnect"
        echo "  status               Show connection status"
        echo "  ip                   Show Tailscale IP"
        echo "  ping <host>          Ping a tailnet host"
        echo ""
        echo "  start                Start daemon"
        echo "  stop                 Stop daemon"
        echo "  restart              Restart daemon"
        echo "  status-svc           Daemon service status"
        ;;
    *)
        sudo ${TAILSCALE_BIN} --socket="\$SOCKET" "\$@"
        ;;
esac
EOF
chmod +x "$WRAPPER"
echo "  wrapper: $WRAPPER"

# --- sudoers drop-in (accumulates all envs) ---
# Rebuild the sudoers file with entries for all existing mutt instances
{
    echo "# Allow $USER to manage tailscale-mutt instances (no password)"
    echo "# Auto-generated by tailscale-mutt-setup.sh — do not edit manually"
    for e in dev stage prod; do
        svc="tailscaled-mutt-${e}"
        sock="/run/tailscale-mutt-${e}.sock"
        if [ -f "/etc/systemd/system/${svc}.service" ]; then
            echo "$USER ALL=(ALL) NOPASSWD: ${TAILSCALE_BIN} --socket=${sock} *"
            echo "$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} start ${svc}"
            echo "$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} stop ${svc}"
            echo "$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} restart ${svc}"
            echo "$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} status ${svc}"
        fi
    done
} > "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"

if ! visudo -cf "$SUDOERS_FILE" &>/dev/null; then
    echo "  ERROR: sudoers syntax invalid, removing"
    rm -f "$SUDOERS_FILE"
    exit 1
fi
echo "  sudoers: $SUDOERS_FILE (updated for all envs)"

echo ""
echo "Done. Connect as '$USER':"
echo "  tailscale-mutt-${ENV} up --authkey=tskey-..."
