#!/bin/bash

# tailscale-client-setup.sh: Set up a secondary Tailscale instance for a client user
# Run as admin (with sudo). Idempotent — safe to re-run.
#
# Creates (all derived from $USER, nothing hardcoded):
#   - systemd service: tailscaled-<user>
#   - wrapper script:  /usr/local/bin/tailscale-<user>
#   - sudoers drop-in: /etc/sudoers.d/tailscale-<user>
#
# The secondary instance uses:
#   - userspace-networking (no TUN device, no iptables, no routing conflicts)
#   - Separate socket, state dir, port
#
# Usage:
#   sudo ./tailscale-client-setup.sh <user>
#
# Then as the client user:
#   tailscale-<user> up --authkey=tskey-auth-...
#   tailscale-<user> status
#   tailscale-<user> down
#
# Client-specific config (tailnet, auth keys) belongs in ~/.clientrc, not here.
# See: docs/tailscale-client.md

set -e

USER="${1:?Usage: $0 <user>}"

STATE_DIR="/var/lib/tailscale-${USER}"
SOCKET="/run/tailscale-${USER}.sock"
SERVICE="tailscaled-${USER}"
PORT=41642
TUN="userspace-networking"
WRAPPER="/usr/local/bin/tailscale-${USER}"
SUDOERS_FILE="/etc/sudoers.d/tailscale-${USER}"
TAILSCALE_BIN="$(command -v tailscale)"
SYSTEMCTL_BIN="$(command -v systemctl)"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: run with sudo"
    exit 1
fi

if ! id "$USER" &>/dev/null; then
    echo "Error: user '$USER' does not exist"
    exit 1
fi

if ! command -v tailscaled &>/dev/null; then
    echo "Error: tailscale not installed"
    exit 1
fi

echo "Setting up secondary Tailscale instance"
echo "  user: $USER"
echo "  port: $PORT"
echo ""

# --- State directory ---
mkdir -p "$STATE_DIR"

# --- systemd service ---
cat > /etc/systemd/system/${SERVICE}.service <<EOF
[Unit]
Description=Tailscale (secondary - ${USER})
After=network-pre.target NetworkManager.service systemd-resolved.service tailscaled.service
Wants=network-pre.target
Requires=tailscaled.service

[Service]
ExecStart=/usr/sbin/tailscaled --state=${STATE_DIR}/tailscaled.state --socket=${SOCKET} --port=${PORT} --tun=${TUN}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "$SERVICE"
echo "  service: $SERVICE"

# --- wrapper script ---
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Tailscale wrapper: secondary instance for ${USER}
# See: docs/tailscale-client.md
SOCKET="${SOCKET}"
SERVICE="${SERVICE}"

case "\$1" in
    start|stop|restart)
        sudo ${SYSTEMCTL_BIN} "\$1" "\$SERVICE"
        ;;
    "")
        echo "Usage: tailscale-${USER} <command>"
        echo ""
        echo "  up [--authkey=...]   Connect to work tailnet"
        echo "  down                 Disconnect"
        echo "  status               Show connection status"
        echo "  ip                   Show Tailscale IP"
        echo "  ping <host>          Ping a tailnet host"
        echo ""
        echo "  start                Start daemon"
        echo "  stop                 Stop daemon"
        echo "  restart              Restart daemon"
        ;;
    *)
        # Block --accept-routes: importing work routes kills personal tailscale routing
        for arg in "\$@"; do
            if [ "\$arg" = "--accept-routes" ] || [ "\$arg" = "--accept-routes=true" ]; then
                echo "ERROR: --accept-routes is blocked on secondary instances."
                echo "It imports subnet routes that conflict with personal tailscale."
                echo "Access work hosts directly by their Tailscale IPs (100.x.x.x)."
                exit 1
            fi
        done
        sudo ${TAILSCALE_BIN} --socket="\$SOCKET" "\$@"
        ;;
esac
EOF
chmod +x "$WRAPPER"
echo "  wrapper: $WRAPPER"

# --- sudoers drop-in ---
cat > "$SUDOERS_FILE" <<EOF
# Allow $USER to manage their secondary tailscale instance (no password)
# Auto-generated by tailscale-client-setup.sh — do not edit manually
$USER ALL=(ALL) NOPASSWD: ${TAILSCALE_BIN} --socket=${SOCKET} *
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} start ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} stop ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} restart ${SERVICE}
$USER ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} status ${SERVICE}
EOF
chmod 440 "$SUDOERS_FILE"

if ! visudo -cf "$SUDOERS_FILE" &>/dev/null; then
    echo "  ERROR: sudoers syntax invalid, removing"
    rm -f "$SUDOERS_FILE"
    exit 1
fi
echo "  sudoers: $SUDOERS_FILE"

# --- Set operator so $USER can run tailscale up/down/set without sudo ---
tailscale --socket="$SOCKET" set --operator="$USER" 2>/dev/null || true
echo "  operator: $USER"

echo ""
echo "Done. Connect as '$USER':"
echo "  tailscale-${USER} up --authkey=tskey-auth-..."
echo ""
echo "Verify personal tailscale is unaffected:"
echo "  tailscale status"
